server:
  port: 8081
spring:
  datasource:
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/schoolDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
