server:
  port: 8082
spring:
  application:
    name: notification-service
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/schoolDb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal: notification.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: notification.routing-key
